services:
  - type: web
    name: rent-spiracy-api
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://rent-spiracy.vercel.app,https://rentspiracy.tech,https://www.rentspiracy.tech
      - key: LOG_LEVEL
        value: INFO
      - key: DATABASE_NAME
        value: rent_spiracy
      - key: MONGO_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
    # Add other environment variables as needed

# Update this file with your own GitHub repository information before deploying
