services:
  - type: web
    name: rent-spiracy-api
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        value: https://rent-spiracy.vercel.app,https://rentspiracy.tech,https://www.rentspiracy.tech,http://localhost:3000
    healthCheckPath: /health
    repo: https://github.com/tash-tech/Rent-Spiracy
    branch: main
    rootDir: backend
    buildFilter:
      paths:
        - backend/**
    # Add other environment variables as needed

# Update this file with your own GitHub repository information before deploying
