services:
  - type: web
    name: rent-spiracy-api
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        value: https://your-frontend-url.vercel.app,http://localhost:3000
    healthCheckPath: /health
    repo: https://github.com/yourusername/Rent-Spiracy
    branch: main
    rootDir: backend
    # Add other environment variables as needed

# Update this file with your own GitHub repository information before deploying
